# Generated by Django 3.2 on 2021-05-20 16:50

from ..models import ICD
from django.db import migrations, models
import csv

filename = '/code/NLPAPI/migrations/ICD10_eng.csv'

def from_csv(apps, schema_editor):
    with open(filename, 'r') as csvfile:
        datareader = csv.reader(csvfile)
        for row in datareader:
            item = ICD(code=row[0],  name=row[1])
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('NLPAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(from_csv)
    ]
