# Generated by Django 3.2 on 2021-05-25 18:34

from django.db import migrations, models
from ..models import ICD
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('NLPAPI', '0002_icd'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            ('create extension fuzzystrmatch')
        ),
        migrations.AlterField(
            model_name='ICD',
            name='name',
            field=models.TextField(),
            preserve_default=True,
        ),
    ]
